### ISSUE TITLE
Support hardware offloading on Smart NIC

### ISSUE THREAD

**Issue by ntnguyencse** [CloudNativeDataPlane/cndp#140]
Hello, I'm interested in XDP and finding a new solution to enhance XDP with hardware support offloading.
I run **"examples/cndpfwd"** but the current version seems to only run in XDP native mode.
Would you show me some way I can run and offload XDP on **Netronome’s Agilio Smart NIC.**

Thank you.

**Comment by KeithWiles** [comment]
Sorry, I have no knowledge of that NIC device and I can not help.

**Comment by maryamtahhan** [comment]
@ntnguyencse Right now CNDP only leverages AF_XDPs default kernel BPF program attached natively to the driver OR it allows you to use your own BPF program loaded on the NIC (at the native hook point) to redirect packets to AF_XDP socket (as long as you share the xskmap for that prog with CNDP)... 

It's not a utility for creating BPF programs and offloading to the NIC... If in theory your NIC is capable of redirecting packets to an AF_XDP socket then CNDP should have no issues interacting and working with your "NIC".

I will highlight that we're looking at CNDP from an application/service point of view rather than it being used for K8s infra

One thing to consider is it's not straight forward to implement complex packet processing pipelines with XDP today, the verifier can be a bit of a pain to work with, and you may not find helpers for everything you need (this of course is growing). You may implement parts but not all of your pipeline with XDP...

**Comment by KeithWiles** [comment]
Going to close this one, if you need to ask another question related to this one, please reopen or open a new issue.
